Enable Translation into other languages
Pray4Movement/prayer-global-porch pull request #339
Opened 2024-04-30 08:05 UTC by corsacca

2024-04-30 09:07 UTC, corsacca commented
See https://github.com/Pray4Movement/prayer-global-porch/issues?q=is%3Aissue+is%3Aopen+Translation+%3E
For remaining places that need to be fixed for translation

2024-05-03 10:11 UTC, squigglybob requested changes
* The un hovered language in the selector is white text.
* clicking on french goes to the re-auth screen
https://www.loom.com/share/daad39eb410946e7adeb6cb9937c998d?sid=48fd71f0-0f7e-4930-bfd3-fa32db22fd05

* share.js l15 needs translating for the share functionality
* as does 'Done' in the share modal 
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/5f6b9f07-d21e-48d6-9e24-d6abe2ad22ab)
* heatmap.js line ~1000 there are a few strings there (seen on the race map when clicking 
 on a state)
* race-list.js I totally hadn't done at all!! sorry 🙁
* and jquery DataTable would need localisation too 😭 '/race_app/race_list/' in active-list.js and race-list.js
* we should probably make these have the same capitalization 
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/db352ca9-771d-4eb6-80ce-20ade1280143)
* I don't think this is for now, but I wonder if we can get translated place names from the mapbox API 
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/d7d6db09-10aa-447f-a33a-4a587494d806)
* in managing prayer relays in the profile area, there are some missing translations
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/8b963847-b02e-4fb1-a554-2994a0a26546)
* what are your thoughts on translating the webform on the contacts page? I think we talked once about maybe having the form just in PG rather than imported from somewhere else, that would certainly make translsating it easier  (and styling it to match the site too).
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/0cafce21-3051-48b1-ae23-d43786dfd1ba)
* just remembered we had a magic-privacy page, i've wrapped them in gettext, but will need translating
* likewise with the 404.php page

I'm loving the translateability and the selector in the nav bar. Can't wait to see it ready and released.
I'm happy to jump over a bit to help with any of these issues when I can.
I also leave the above up to you whether they need to be in this PR or punted to another issue

2024-05-03 11:17 UTC, corsacca commented on utilities/global-utilities.php
> +        $lang = sanitize_text_field( wp_unslash( $_GET['lang'] ) );
The current strategy might not even need the ?lang=fr. That is useful in links handed out. The lang is set in the cookie and the site feels native.
/fr/ strategy requires all the pages all the time to have that added to the path. And makes some functions harder like  `dt_url_path()`

2024-05-03 11:18 UTC, corsacca commented on pages/user/user-profile.php
> +            'map_key' => DT_Mapbox_API::get_key(),
Yeah, I'd like to move all the enqueues to uses this strategy

2024-05-03 11:36 UTC, corsacca commented on pages/pray/lap.js
> +
We are not loading D.T's shared-functions.js on all the P.G front end pages. 
But I'll move these to P.G's global functions to be used throughout.
The translate function does depend on the page's localized object.

2024-05-03 14:10 UTC, squigglybob commented on utilities/global-utilities.php
> +        $lang = sanitize_text_field( wp_unslash( $_GET['lang'] ) );
ah yeah I like that better, let's keep it that way.

2024-05-07 09:42 UTC, corsacca commented
After a bunch of changes
- all the english text i can find is waiting on the changes to be pushed to weblate for translation
- we won't translate the webform, that will require a bunch of work on the webform plugin.
- the remaining translation issues are logged here: https://github.com/Pray4Movement/prayer-global-porch/issues?q=is%3Aissue+is%3Aopen+label%3Atranslation

2024-05-08 10:58 UTC, squigglybob requested changes
It's all looking good. I like the idea of using the bootsrap  dropdown, it looks nicer and solves some issues.
I changed up the styles slightly and switched out the icon.

* on the page /race_app/race_map/
there might be a duplicated heatmap.js declaration going  on
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/5925735c-46ba-414c-8cb6-bc396ab6c41a)
* and on the active  relays page and the lap.js page
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/c6c3e5d2-5968-4ce9-b398-2c3bff4178ec)
* wierdly when I click on status link in menu when not on the home page it works fine, but when on the home page it has a jquery-ui missing error
![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/9e0f8857-991e-4f11-965c-4966235b9a6e)

I'm guessing something is up with the script loadings, but other than that it's all looking good bro 😃

2024-05-08 13:19 UTC, merged

2024-05-08 13:19 UTC, squigglybob commented
looks good bro thanks 😃 🎉